### ISSUE TITLE
Path-dependent type get handled as type lambda

### ISSUE THREAD

**Issue by c-solo** [zio/izumi-reflect#292]
Here is simple test for reproducing:
```scala
    trait Foo {
      class Inner()
    }
    object FooObj extends Foo

    def test[A <: Foo](a: A): Tag[a.Inner] = Tag.tagFromTagMacro[a.Inner]

    test(FooObj) shouldBe Tag.tagFromTagMacro[FooObj.Inner]
```
```
a::Inner is not a type lambda, it cannot be parameterized
java.lang.IllegalArgumentException: a::Inner is not a type lambda, it cannot be parameterized
	at izumi.reflect.macrortti.LightTypeTagRef.applyParameters(LightTypeTagRef.scala:199)
	at izumi.reflect.macrortti.LightTypeTagRef.applyParameters$(LightTypeTagRef.scala:184)
	at izumi.reflect.macrortti.LightTypeTagRef$NameReference.applyParameters(LightTypeTagRef.scala:297)
	at izumi.reflect.macrortti.LightTypeTagRef.applySeq(LightTypeTagRef.scala:177)
	at izumi.reflect.macrortti.LightTypeTagRef.applySeq$(LightTypeTagRef.scala:175)
	at izumi.reflect.macrortti.LightTypeTagRef$NameReference.applySeq(LightTypeTagRef.scala:297)
	at izumi.reflect.macrortti.LightTypeTagRef.combine(LightTypeTagRef.scala:31)
	at izumi.reflect.macrortti.LightTypeTagRef.combine$(LightTypeTagRef.scala:30)
	at izumi.reflect.macrortti.LightTypeTagRef$NameReference.combine(LightTypeTagRef.scala:297)
	at izumi.reflect.macrortti.LightTypeTag.combine(LightTypeTag.scala:104)
	at izumi.reflect.Tag$.appliedTag(Tags.scala:139)
```
Not sure about importance of this case, but maybe you guys should be aware of this.

Scala 2.13, Java 17.0.3, izumi-reflect_2.13-1.1.3

**Comment by pshirshov** [comment]
Thanks for reporting. That definitely looks strange.

**Comment by pshirshov** [comment]
I'm not sure how exactly you managed to get such stack.

For me your code works as expected, the tags are not equal but that's a limitation which is hard to overcome. But there is nothing similar to your trace:

```
Tag[a::Inner] did not equal Tag[FooObj::Inner]
ScalaTestFailureLocation: izumi.reflect.test.LightTypeTagTest at (LightTypeTagTest.scala:37)
Expected :Tag[FooObj::Inner]
Actual   :Tag[a::Inner]
<Click to see difference>

org.scalatest.exceptions.TestFailedException: Tag[a::Inner] did not equal Tag[FooObj::Inner]
	at org.scalatest.Assertions.newAssertionFailedException(Assertions.scala:472)
	at org.scalatest.Assertions.newAssertionFailedException$(Assertions.scala:471)
	at org.scalatest.Assertions$.newAssertionFailedException(Assertions.scala:1231)
	at org.scalatest.Assertions$AssertionsHelper.macroAssert(Assertions.scala:1295)
	at izumi.reflect.test.LightTypeTagTest.$anonfun$new$2(LightTypeTagTest.scala:37)
```

Could you provide a full repro please?

**Comment by neko-kai** [comment]
> izumi-reflect_2.13-1.1.3

This might be occuring only on an old version of `izumi-reflect`. The current version is `2.1.1`
