### ISSUE TITLE
Support tuple tags on dotty 0.26.0-RC1

### ISSUE THREAD

**Issue by neko-kai** [zio/izumi-reflect#38]
Getting an exception when trying to access definition tree of Tuple.

```
Error:(12, 10) Exception occurred while executing macro expansion.
java.lang.AssertionError: assertion failed
	at dotty.DottyPredef$.assertFail(DottyPredef.scala:16)
	at dotty.tools.dotc.ast.tpd$.polyDefDef(tpd.scala:239)
	at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:225)
	at dotty.tools.dotc.ast.tpd$.DefDef(tpd.scala:222)
	at dotty.tools.dotc.tastyreflect.FromSymbol$.classDef(FromSymbol.scala:33)
	at dotty.tools.dotc.tastyreflect.FromSymbol$.definitionFromSym(FromSymbol.scala:16)
	at dotty.tools.dotc.tastyreflect.ReflectionCompilerInterface.Symbol_tree(ReflectionCompilerInterface.scala:1672)
	at dotty.tools.dotc.tastyreflect.ReflectionCompilerInterface.Symbol_tree(ReflectionCompilerInterface.scala:1671)
	at scala.tasty.Reflection$SymbolOps$.tree(Reflection.scala:2161)
	at izumi.reflect.dottyreflection.Inspector.inspectTType(DbInspector.scala:55)
	at izumi.reflect.dottyreflection.Inspector.inspectTree(DbInspector.scala:121)
	at izumi.reflect.dottyreflection.Inspector.buildTypeRef(DbInspector.scala:42)
	at izumi.reflect.dottyreflection.TypeInspections$.apply(DbInspector.scala:265)
	at izumi.reflect.dottyreflection.Inspect$.inspectAny(DbInspector.scala:21)
  inspect[(Double, Double)]
```

**Comment by DamianReeves** [comment]
Have you had a chance to look into this? This seems to be blocking the dotty upgrade for ZIO.

**Comment by pshirshov** [comment]
Not yet, will try to look at that this weekend.

**Comment by neko-kai** [comment]
@DamianReeves This is an upstream bug without a straightforward way to work around it seems, unless we can find a way to totally omit inspecting trees, which with the current tasty-reflect I think we cannot (/cc @pshirshov).
I've posted a reproduction upstream - https://github.com/lampepfl/dotty/issues/9206

**Comment by neko-kai** [comment]
There's a new dotty release with the fix merged, `0.26.0-RC1`: https://dotty.epfl.ch/blog/2020/07/27/26th-dotty-milestone-release.html
should be able to restart publishing for 0.26+ now

**Comment by adamgfraser** [comment]
@neko-kai Any change we could get a release with this fix so we could publish for the latest Dotty version when we do the ZIO 1.0 release on Monday?

**Comment by neko-kai** [comment]
Closed by #56

**Comment by neko-kai** [comment]
@adamgfraser Seems like it. Please check version `1.0.0-M5` for dotty `0.26.0-RC1`

**Comment by adamgfraser** [comment]
@neko-kai Great! Will do.
