### ISSUE TITLE
Tag generation fails for Scala Array

### ISSUE THREAD

**Issue by improved-broccoli** [zio/izumi-reflect#474]
Scala version: 3.4.2
Izumi reflect version: 2.3.8 (transitively from zio-mock)

Writing a ZIO Mock using the Scala Array type makes the compiler crash with:

<details>

<summary>Compiler output</summary>

```
java.lang.AssertionError: assertion failed: class Array
	at scala.runtime.Scala3RunTime$.assertFailed(Scala3RunTime.scala:8)
	at dotty.tools.backend.jvm.BCodeHelpers.primitiveOrClassToBType$1(BCodeHelpers.scala:717)
	at dotty.tools.backend.jvm.BCodeHelpers.dotty$tools$backend$jvm$BCodeHelpers$$typeToTypeKind(BCodeHelpers.scala:737)
	at dotty.tools.backend.jvm.BCodeHelpers$BCInnerClassGen.toTypeKind(BCodeHelpers.scala:202)
	at dotty.tools.backend.jvm.BCodeHelpers$BCInnerClassGen.toTypeKind$(BCodeHelpers.scala:130)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.toTypeKind(BCodeSkelBuilder.scala:134)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genConstant(BCodeBodyBuilder.scala:582)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadTo(BCodeBodyBuilder.scala:451)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:304)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.loop$1(BCodeBodyBuilder.scala:1210)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1217)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:836)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadTo(BCodeBodyBuilder.scala:386)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadTo(BCodeBodyBuilder.scala:466)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:304)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadTo(BCodeBodyBuilder.scala:321)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:304)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:116)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlockTo$$anonfun$1(BCodeBodyBuilder.scala:1094)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlockTo(BCodeBodyBuilder.scala:1094)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadTo(BCodeBodyBuilder.scala:458)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:304)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.loop$1(BCodeBodyBuilder.scala:1210)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadArguments(BCodeBodyBuilder.scala:1217)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genApply(BCodeBodyBuilder.scala:836)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadTo(BCodeBodyBuilder.scala:386)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoad(BCodeBodyBuilder.scala:304)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genStat(BCodeBodyBuilder.scala:116)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlockTo$$anonfun$1(BCodeBodyBuilder.scala:1094)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genBlockTo(BCodeBodyBuilder.scala:1094)
	at dotty.tools.backend.jvm.BCodeBodyBuilder$PlainBodyBuilder.genLoadTo(BCodeBodyBuilder.scala:458)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.emitNormalMethodBody$1(BCodeSkelBuilder.scala:893)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genDefDef(BCodeSkelBuilder.scala:916)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:693)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen$$anonfun$1(BCodeSkelBuilder.scala:699)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.gen(BCodeSkelBuilder.scala:699)
	at dotty.tools.backend.jvm.BCodeSkelBuilder$PlainSkelBuilder.genPlainClass(BCodeSkelBuilder.scala:293)
	at dotty.tools.backend.jvm.CodeGen.genClass(CodeGen.scala:154)
	at dotty.tools.backend.jvm.CodeGen.genClassDef$1(CodeGen.scala:62)
	at dotty.tools.backend.jvm.CodeGen.genClassDefs$1(CodeGen.scala:117)
	at dotty.tools.backend.jvm.CodeGen.genClassDefs$1$$anonfun$1(CodeGen.scala:115)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.backend.jvm.CodeGen.genClassDefs$1(CodeGen.scala:115)
	at dotty.tools.backend.jvm.CodeGen.genUnit(CodeGen.scala:120)
	at dotty.tools.backend.jvm.GenBCode.run(GenBCode.scala:83)
	at dotty.tools.dotc.core.Phases$Phase.runOn$$anonfun$1(Phases.scala:354)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.immutable.List.foreach(List.scala:333)
	at dotty.tools.dotc.core.Phases$Phase.runOn(Phases.scala:360)
	at dotty.tools.backend.jvm.GenBCode.runOn(GenBCode.scala:91)
	at dotty.tools.dotc.Run.runPhases$1$$anonfun$1(Run.scala:315)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:15)
	at scala.runtime.function.JProcedure1.apply(JProcedure1.java:10)
	at scala.collection.ArrayOps$.foreach$extension(ArrayOps.scala:1323)
	at dotty.tools.dotc.Run.runPhases$1(Run.scala:337)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$1(Run.scala:350)
	at dotty.tools.dotc.Run.compileUnits$$anonfun$adapted$1(Run.scala:360)
	at dotty.tools.dotc.util.Stats$.maybeMonitored(Stats.scala:69)
	at dotty.tools.dotc.Run.compileUnits(Run.scala:360)
	at dotty.tools.dotc.Run.compileSources(Run.scala:261)
	at dotty.tools.dotc.Run.compile(Run.scala:246)
	at dotty.tools.dotc.Driver.doCompile(Driver.scala:37)
	at dotty.tools.xsbt.CompilerBridgeDriver.run(CompilerBridgeDriver.java:141)
	at dotty.tools.xsbt.CompilerBridge.run(CompilerBridge.java:22)
	at sbt.internal.inc.AnalyzingCompiler.compile(AnalyzingCompiler.scala:91)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$7(MixedAnalyzingCompiler.scala:193)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at sbt.internal.inc.MixedAnalyzingCompiler.timed(MixedAnalyzingCompiler.scala:248)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4(MixedAnalyzingCompiler.scala:183)
	at sbt.internal.inc.MixedAnalyzingCompiler.$anonfun$compile$4$adapted(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.JarUtils$.withPreviousJar(JarUtils.scala:239)
	at sbt.internal.inc.MixedAnalyzingCompiler.compileScala$1(MixedAnalyzingCompiler.scala:163)
	at sbt.internal.inc.MixedAnalyzingCompiler.compile(MixedAnalyzingCompiler.scala:211)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileInternal$1$adapted(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5(Incremental.scala:180)
	at sbt.internal.inc.Incremental$.$anonfun$apply$5$adapted(Incremental.scala:178)
	at sbt.internal.inc.Incremental$$anon$2.run(Incremental.scala:464)
	at sbt.internal.inc.IncrementalCommon$CycleState.next(IncrementalCommon.scala:116)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:56)
	at sbt.internal.inc.IncrementalCommon$$anon$1.next(IncrementalCommon.scala:52)
	at sbt.internal.inc.IncrementalCommon.cycle(IncrementalCommon.scala:263)
	at sbt.internal.inc.Incremental$.$anonfun$incrementalCompile$8(Incremental.scala:419)
	at sbt.internal.inc.Incremental$.withClassfileManager(Incremental.scala:506)
	at sbt.internal.inc.Incremental$.incrementalCompile(Incremental.scala:406)
	at sbt.internal.inc.Incremental$.apply(Incremental.scala:172)
	at sbt.internal.inc.IncrementalCompilerImpl.compileInternal(IncrementalCompilerImpl.scala:534)
	at sbt.internal.inc.IncrementalCompilerImpl.$anonfun$compileIncrementally$1(IncrementalCompilerImpl.scala:488)
	at sbt.internal.inc.IncrementalCompilerImpl.handleCompilationError(IncrementalCompilerImpl.scala:332)
	at sbt.internal.inc.IncrementalCompilerImpl.compileIncrementally(IncrementalCompilerImpl.scala:425)
	at sbt.internal.inc.IncrementalCompilerImpl.compile(IncrementalCompilerImpl.scala:137)
	at sbt.Defaults$.compileIncrementalTaskImpl(Defaults.scala:2371)
	at sbt.Defaults$.$anonfun$compileIncrementalTask$2(Defaults.scala:2321)

	at sbt.internal.server.BspCompileTask$.$anonfun$compute$1(BspCompileTask.scala:31)
```
</details>

The error comes from the makeTag Macro.
Here is a demo: https://scastie.scala-lang.org/ugTtSPC9STqinqMGS1nieQ

**Comment by pshirshov** [comment]
I have a strong feeling that we've already reported that as a bug in dotty. 
UPD: can't find it, could you report it there?..

**Comment by pshirshov** [comment]
@jdegoes I've reported the issue to the compiler team, this is up to them to resolve. So, I think the bounty should be removed from this issue.

**Comment by som-snytt** [comment]
or, the bounty should be doubled if the fix is upstream! because a. the solution is harder and b. it is more valuable because it benefits more people. plus c. if the compiler team doesn't need to supply the fix, they are free to pursue other work.

**Comment by pshirshov** [comment]
Anyway, the bounty shouldn't be here, this issue cannot be solved on i-r level, this is a bug in the compiler.

**Comment by jchyb** [comment]
Looks like the Array type parameter is lost somewhere before that Array type is applied to the `classOf` method in the macro.

**Comment by goshacodes** [comment]
/attempt #474


<div id="algora-attempt" />

<details>
  <summary>Options</summary>
  <ul>
    <li>
      <a href="https://console.algora.io/api/bounties/cm38xpppp0002mh03tgjdtyh3/cancel-attempt">
        Cancel my attempt
      </a>
    </li>
  </ul>
</details>

**Comment by neko-kai** [comment]
Seems like the issue was with izumi-reflect after all and can't be fixed on the compiler side – as found out in the linked dotty issue. I think it's fair for me to take the bounty with the above fix, since I fixed the underlying issue for all proper types on Scala 3 and uncovered and fixed another Array-related issue on Scala 2 in the process.

**Comment by goshacodes** [comment]
Guys, doing this after I made a solution which works and claimed bounty - you rejected it with reason 'it should be fixed in the compiler' is at least disrespectful

> Seems like the issue was with izumi-reflect after all and can't be fixed on the compiler side – as found out in the linked dotty issue. I think it's fair for me to take the bounty with the above fix, since I fixed the underlying issue for all proper types on Scala 3 and uncovered and fixed another Array-related issue on Scala 2 in the process.

**Comment by pshirshov** [comment]
Well, my opinion still stands. Originally we didn't know what exactly the issue is. As per the failure was only triggered by a handful of select types, we were sure that it's a compiler bug. 

Then we got a clarification from the compiler team but still were sure that it's a compiler bug. The compiler behaviour was/is inconsistent, in some cases it happily takes unapplied types into `classOf`, in some cases it fails. Because it was working most of the time, my assumption was that it should work always. 

The compiler team decided otherwise and they think that the right course of action would be to prohibit usages they consider incorrect (and which are still perfectly correct from JVM point of view, but I understand where they see the unsoundness), I might not agree this their opinion but I respect it. I offered them to take this bounty but they refused. A reasonable amount of time passed since last update from the compiler side and there were no new attempts of a better P/R.

@neko-kai baked a fix which I consider correct. He also found and fixed similar issue in Scala 2 macros. While your P/R would make a workaround for the particular crash with arrays, it does not cover the whole extent of the problem. E.g. we cannot be sure that the crash is only triggered by arrays and now we know that we were building an unsound AST. There is a possibility that it would fail on some other types and your workaround won't work in that case. @neko-kai 's solution will work, because it builds sound trees always. I don't think it is "disrespectful" in any way, I understand your frustration but this is not about getting an easy dollar, this is about delivering the best solution possible, as a lot of stuff depends both on compiler correctness and our humble library.

@jdegoes , could you chip in as an arbiter?

**Comment by neko-kai** [comment]
@goshacodes I won't be quite sure of that. You've had the same information as I did (jchyb's November message above saying that we lose type parameters), yet your solution contains minimal investigative work - just always returning Array\[?\] for arrays - which loses specific array class and does not pass the additional tests added in my solution:

```scala
assert(Tag[Array[Byte]].closestClass eq classOf[Array[Byte]])
assert(Tag[Array[Int]].closestClass eq classOf[Array[Int]])
```

So, while your solution did work for the specific issue (even though we would still not accept without modification, due to needing to be fixed to pass the above tests) – and it wasn't a fraud attempt like the laborious ChatGPT contribution we got in https://github.com/zio/izumi-reflect/pull/518/files – you could argue there's a slight disrespect in trying to quickly close the issue with a special case while eschewing additional investigative work. Investigative work was done by jchyb – who did the initial investigation, but refused the bounty – and additional investigative work was done by me, who fixed the issue for all array types, not just Array\[?\] and uncovered a similar issue on Scala 2.

I'm thankful for you trying to contribute, but I don't agree that you were wronged here.

**Comment by goshacodes** [comment]
I haven't seen a word from maintainer claiming that my work is not full, @pshirshov said it is compiler thing to fix. And now another maintainer just makes a full implementation and it is not compiler thing to fix anymore. If this gets merged and you claim the bounty for me personally this looks like a fraud, no offend. Anyway I'll not commit my time to this project anymore and go find something different

> @goshacodes I won't be quite sure of that. You've had the same information as I did (jchyb's November message above saying that we lose type parameters), yet your solution contains minimal investigative work - just always returning Array\[?\] for arrays - which loses specific array class and does not pass the additional tests added in my solution:
> 
> ```scala
> assert(Tag[Array[Byte]].closestClass eq classOf[Array[Byte]])
> assert(Tag[Array[Int]].closestClass eq classOf[Array[Int]])
> ```
> 
> So, while your solution did work for the specific issue (even though we would still not accept without modification, due to needing to be fixed to pass the above tests) – and it wasn't a fraud attempt like the laborious ChatGPT contribution we got in https://github.com/zio/izumi-reflect/pull/518/files – you could argue there's a slight disrespect in trying to quickly close the issue with a special case while eschewing additional investigative work. Investigative work was done by jchyb – who did the initial investigation, but refused the bounty – and additional investigative work was done by me, who fixed the issue for all array types, not just Array\[?\] and uncovered a similar issue on Scala 2.
> 
> I'm thankful for you trying to contribute, but I don't agree that you were wronged here.

**Comment by pshirshov** [comment]
Well, if you call this "fraud" I might just repeat that your implementation was a half-baked workaround which won't work for all the cases. I would prefer this to be solved at compiler level, the compiler team decided that they will prohibit "unsound" `classOf`s (which is still better than current behavior), so we had to solve it on our level.

>  Anyway I'll not commit my time to this project anymore 

Whatever you might desire. Many things depend on I/R but so far we haven't been paid for this six years long work nor received many thanks. This stuff is not about bounties. My position was clear from the beginning - the bounty shouldn't have been on this issue, but if it is, it's fair to award it to the first complete implementation.

**Comment by goshacodes** [comment]
So did you mention any cases which won't work with it? My PR fully solves problem mentioned in this issue. No more, no less, because there was no more things mentioned. Even if it is a workaround. If you didn't stop me, I could do it better. No guidance on how to make it better. Instead one maintainer saying it is not compiler thing to fix and another fixing it the 'right' way

> Well, if you call this "fraud" I might just repeat that your implementation was a half-baked workaround which won't work for all the cases. I would prefer this to be solved at compiler level, the compiler team decided that they will prohibit "unsound" `classOf`s (which is still better than current behavior), so we had to solve it on our level.
> 
> >  Anyway I'll not commit my time to this project anymore 
> 
> Whatever you might desire. Many things depend on I/R but so far we haven't been paid for this six years long work nor received many thanks. This stuff is not about bounties. My position was clear from the beginning - the bounty shouldn't have been on this issue, but if it is, it's fair to award it to the first complete implementation.

**Comment by goshacodes** [comment]
I don't really care about bounty, but all this situation is nonsense. And that's totally not a good way of onboarding new people to the project to fix the issues

**Comment by pshirshov** [comment]
It happens. 
I stated my position clear in the very beginning of this thread: https://github.com/zio/izumi-reflect/issues/474#issuecomment-2466461395
You took a risk of trying to make a contribution to an issue where the project lead specifically said that he doesn't want the bounty to be assigned.

**Comment by goshacodes** [comment]
So this is a coincidence @neko-kai starts working on same things when new people come and try to fix something?
https://github.com/zio/izumi-reflect/pull/519

**Comment by pshirshov** [comment]
His branch was opened earlier (25th of January) than the attempt was made (two weeks ago). Also compare the size of the patches. He should have marked his attempt though.

I've asserted several times, that this project is complex and an in-depth knowledge is required before making any P/R attempts. Half of the issues are still open for a reason, the solutions won't be trivial.

**Comment by pshirshov** [comment]
#379, #384 - I think these are the only two issues which can be done easily, but one of them still would require some understanding of our type lambda representation model.

**Comment by pshirshov** [comment]
Ah, yes, #350 is another simple issue with no serious attempts. I guess eventually we will have to do them all, but trust me, that's not because we urgently need a couple of hundred dollars. This project took multiple months stretched over 6 years and we weren't paid for this job.

**Comment by jdegoes** [comment]
@pshirshov Do you think it would be possible to guide @goshacodes down the path of the best-possible-fix? He seems eager to solve this problem, which I am happy about.

Or do you think that it would be easier and faster for you to solve this problem?

**Comment by goshacodes** [comment]
Ok, sorry for that. I think the process should be improved somehow to be clear for all parties inner or outer. If maintainer works on issue probably there should be some note on that

> His branch was opened earlier (25th of January) than the attempt was made (two weeks ago). Also compare the size of the patches. He should have marked his attempt though.
> 
> I've asserted several times, that this project is complex and an in-depth knowledge is required before making any P/R attempts. Half of the issues are still open for a reason, the solutions won't be trivial.

**Comment by pshirshov** [comment]
It's already solved by @neko-kai

**Comment by goshacodes** [comment]
I personally want to end this discussion and make excuses to @pshirshov and @neko-kai for these rough and not very pleasant talks from my side. Really sorry again guys. I just don't want to insult you more. Maybe I will try to contribute to this project some time later and really hope it will be pleasant for us all. Just merge it and let's finish it
